# This is a basic workflow to help you get started with Actions

name: 运行python脚本-1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: echo "GITHUB_WORKSPACE:\n|${GITHUB_WORKSPACE}|"
      - run: pwd
      - run: ls -a
      - run: rm -rf t1
      - run: rm -rf t2
      - run: mkdir t2
      - run: echo "new file" > t2/new1.txt
      - run: ls -a
      - run: ls -a t2
      - name: ds ${{ secrets.SECRET1 }}
        run: |
          echo ${{ secrets.SECRET1 }}
          echo ${{ github.ref }}
      # 把密码传给python 脚本
      - run: python py1.py 11 222 333 ${{ secrets.SECRET1 }}
      - run: git add t2/new1.txt
      - run: git commit -m "上传结果:`date +%Y%m%d-%H%M%S`|"
      - run: git push

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run python脚本
        run: python py1.py 12 434 54
